### PR TITLE
#160178341 Create users page

### PR DESCRIPTION
**Pull request by davishooly**
**what does this PR do?**

creates a user page

**Description of Task to be completed?**

Tasks completed:
-view list of foods
-users can be able to place food orders
-a link to users order history
-a link to  how-it-works section

**How should this be manually tested?**

clone the repo as below:
```
git clone -b ft-users-160178341 git@github.com:davishooly/FastFoodFast.git

```
cd UI/pages
open `users.html` in your browser

**What are the relevant pivotal tracker stories?**
[#160178341](https://www.pivotaltracker.com/n/projects/2178116)

**Screenshots (if appropriate)**
screenshot from 2018-08-31 15-33-15

### CODE REVIEW

**Comment by kelvinndmo** [comment]
nice UI good work man....place order button color change it a shouting color like crimson

**Comment by izoo** [comment]
cool  and great UI men....keep the fire burning

**Comment by davishooly** [comment]
wazi novak

**Comment by EmmanuelBeja** [comment]
love the shadowy layer look on the food. great job

**Pull request merged**
