### PR TITLE
Ft dashboard 160166188

### PR DESCRIPTION
**Pull request by davishooly**
**what does this PR do?**

creates a dashboard

**Description of Task to be completed?**

Tasks completed:
-view list of food orders
-add, delete and edit food items
-accept and reject food offers

**How should this be manually tested?**

clone the repo as below:
```
git clone -b ft-dashboard-160166188 git@github.com:davishooly/FastFoodFast.git

```
cd UI/pages
open `dashboard.html` in your browser

**What are the relevant pivotal tracker stories?**
[#160166188](https://www.pivotaltracker.com/n/projects/2178116)

**Screenshots (if appropriate)**

screenshot from 2018-08-30 19-07-54
screenshot from 2018-08-30 19-07-30
screenshot from 2018-08-30 19-08-17
screenshot from 2018-08-30 19-17-23

### CODE REVIEW

**Comment by danielotieno** [comment]
This is Awesome!!

**Comment by NgachaIan** [comment]
Keep up the good work!

**Comment by markmumo** [comment]
Nice work

**Comment by kelvinndmo** [comment]
good work

**Comment by bettblake08** [comment]
Thats good work

**Comment by nesh-dev** [comment]
This is good work the UI looks real good

**Pull request merged**
