### PR TITLE
#158358043 Create a landing page

### PR DESCRIPTION
**Pull request by davishooly**
**what does this PR do?**

creates a landing page

**Description of Task to be completed?**

Tasks completed:
-A signup link
-How it works section
-footer section

**How should this be manually tested?**

clone the repo as below:
```
git clone -b ft-landing-158358043 git@github.com:davishooly/FastFoodFast.git

```
cd UI
open `index.html` in your browser

**What are the relevant pivotal tracker stories?**
[#158358043](https://www.pivotaltracker.com/n/projects/2178116)

**Screenshots (if appropriate)**

screenshot from 2018-08-29 13-13-16
screenshot from 2018-08-29 13-13-39

### CODE REVIEW

**Comment by mashafrancis** [comment]
Nice one. Looks awesome.

**Comment by vincentmuriuki** [comment]
Looks great

**Comment by ThaDeveloper** [comment]
Nice UI

**Comment by ThaDeveloper** [comment]
Great stuff!

**Comment by kmwangemi** [comment]
looks great

**Comment by PromasterGuru** [comment]
Awesome

**Comment by danielotieno** [comment]
Neat!, Great work

**Comment by salma-nyagaka** [comment]
Nice

**Pull request merged**
